name: Tag

on:
    push:
        branches: ["main"]
        paths:
            - "**.go"
            - "go.mod"
            - "go.sum"
            - ".github/workflows/tag.yml"
    workflow_dispatch:

permissions:
    contents: write
    id-token: write

concurrency:
    group: tag
    cancel-in-progress: true

jobs:
    tag:
        environment:
            name: github-pages
        runs-on: ubuntu-latest
        steps:
          - name: Install jq
            run: sudo apt-get install jq
          - name: Setup Go environment
            uses: actions/setup-go@v4.1.0
            with:
              go-version: ">=1.21.5"
              cache: false
              architecture: x64
          - name: Checkout
            uses: actions/checkout@v3
          - name: Tidy
            run: go mod tidy
          - name: Check for version change
            run: |
              git config --global user.email "actions@github.com"
              git config --global user.name "GitHub Actions"
              current=v$(go run cmd/hl/main.go -v 2>&1)
              tags=$(curl https://api.github.com/repos/Frank-Mayer/serve/tags)
              latest=$(echo $tags | jq -r '.[0].name')
              if [ "$current" = "$latest" ]; then
                echo "No version change detected. Exiting."
                exit 0
              fi
              echo "Version change detected. Tagging. $latest -> $current"
              git tag -a $current -m "Release $current"
              git push origin $current
              curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/Frank-Mayer/serve/releases \
              -d '{"tag_name":"'"$current"'","name":"'"$current"'","draft":false,"prerelease":false,"generate_release_notes":false}'
